apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z57q9aqj3-python
  janus-idp.io/tekton: z57q9aqj3-python
  backstage.io/kubernetes-id: z57q9aqj3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z57q9aqj3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
